// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrqzA-CCcobY-ruxNTg_P9o2uI1HTsEZA',
    appId: '1:203833032621:web:651405918bdfa20b06eb24',
    messagingSenderId: '203833032621',
    projectId: 'ecommerceapp-78dc0',
    authDomain: 'ecommerceapp-78dc0.firebaseapp.com',
    storageBucket: 'ecommerceapp-78dc0.appspot.com',
    measurementId: 'G-317KY3XR1D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLLSCdHcM4JYFWLZgPwbXQcopRJIIxQ2o',
    appId: '1:203833032621:android:7d12a4602f0af05506eb24',
    messagingSenderId: '203833032621',
    projectId: 'ecommerceapp-78dc0',
    storageBucket: 'ecommerceapp-78dc0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6rMQ7qf3P8qT6dv3qSZVazxSljFBQKS0',
    appId: '1:203833032621:ios:a7958ea8a691062206eb24',
    messagingSenderId: '203833032621',
    projectId: 'ecommerceapp-78dc0',
    storageBucket: 'ecommerceapp-78dc0.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6rMQ7qf3P8qT6dv3qSZVazxSljFBQKS0',
    appId: '1:203833032621:ios:a7958ea8a691062206eb24',
    messagingSenderId: '203833032621',
    projectId: 'ecommerceapp-78dc0',
    storageBucket: 'ecommerceapp-78dc0.appspot.com',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBrqzA-CCcobY-ruxNTg_P9o2uI1HTsEZA',
    appId: '1:203833032621:web:e6fcfd9b0a0e99ce06eb24',
    messagingSenderId: '203833032621',
    projectId: 'ecommerceapp-78dc0',
    authDomain: 'ecommerceapp-78dc0.firebaseapp.com',
    storageBucket: 'ecommerceapp-78dc0.appspot.com',
    measurementId: 'G-B78G4C05NW',
  );
}
